In [1]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt

In [2]:
timewindow=20
# old general
old_1 = pd.DataFrame(np.loadtxt('o1-76-si.txt'), columns=['time','gait'])
old_1['participant_id'] = 'old_1'
old_1['label'] = 'old_general'
old_1['group']=np.divmod(np.arange(len(old_1)),timewindow)[0]+1
old_1.to_csv('dataset_old_1.csv')

old_2 = pd.DataFrame(np.loadtxt('o2-74-si.txt'), columns=['time','gait'])
old_2['participant_id'] = 'old_2'
old_2['label'] = 'old_general'
old_2['group']=np.divmod(np.arange(len(old_2)),timewindow)[0]+1
old_2.to_csv('dataset_old_2.csv')

old_3 = pd.DataFrame(np.loadtxt('o3-75-si.txt'), columns=['time','gait'])
old_3['participant_id'] = 'old_3'
old_3['label'] = 'old_general'
old_3['group']=np.divmod(np.arange(len(old_3)),timewindow)[0]+1
old_3.to_csv('dataset_old_3.csv')

old_4 = pd.DataFrame(np.loadtxt('o4-77-si.txt'), columns=['time','gait'])
old_4['participant_id'] = 'old_4'
old_4['label'] = 'old_general'
old_4['group']=np.divmod(np.arange(len(old_4)),timewindow)[0]+1
old_4.to_csv('dataset_old_4.csv')

old_5 = pd.DataFrame(np.loadtxt('o5-71-si.txt'), columns=['time','gait'])
old_5['participant_id'] = 'old_5'
old_5['label'] = 'old_general'
old_5['group']=np.divmod(np.arange(len(old_5)),timewindow)[0]+1
old_5.to_csv('dataset_old_5.csv')

In [3]:
# young general
young_1 = pd.DataFrame(np.loadtxt('y1-23-si.txt'), columns=['time','gait'])
young_1['participant_id'] = 'young_1'
young_1['label'] = 'young_general'
young_1['group']=np.divmod(np.arange(len(young_1)),timewindow)[0]+1
young_1.to_csv('dataset_young_1.csv')

young_2 = pd.DataFrame(np.loadtxt('y2-29-si.txt'), columns=['time','gait'])
young_2['participant_id'] = 'young_2'
young_2['label'] = 'young_general'
young_2['group']=np.divmod(np.arange(len(young_2)),timewindow)[0]+1
young_2.to_csv('dataset_young_2.csv')

young_3 = pd.DataFrame(np.loadtxt('y3-23-si.txt'), columns=['time','gait'])
young_3['participant_id'] = 'young_3'
young_3['label'] = 'young_general'
young_3['group']=np.divmod(np.arange(len(young_3)),timewindow)[0]+1
young_3.to_csv('dataset_young_3.csv')

young_4 = pd.DataFrame(np.loadtxt('y4-21-si.txt'), columns=['time','gait'])
young_4['participant_id'] = 'young_4'
young_4['label'] = 'young_general'
young_4['group']=np.divmod(np.arange(len(young_4)),timewindow)[0]+1
young_4.to_csv('dataset_young_4.csv')

young_5 = pd.DataFrame(np.loadtxt('y5-26-si.txt'), columns=['time','gait'])
young_5['participant_id'] = 'young_5'
young_5['label'] = 'young_general'
young_5['group']=np.divmod(np.arange(len(young_5)),timewindow)[0]+1
young_5.to_csv('dataset_young_5.csv')

In [4]:
# old parkinson
parkinson_1 = pd.DataFrame(np.loadtxt('pd1-si.txt'), columns=['time','gait'])
parkinson_1['participant_id'] = 'parkinson_1'
parkinson_1['label'] = 'old_parkinson'
parkinson_1['group']=np.divmod(np.arange(len(parkinson_1)),timewindow)[0]+1
parkinson_1.to_csv('dataset_parkinson_1.csv')

parkinson_2 = pd.DataFrame(np.loadtxt('pd2-si.txt'), columns=['time','gait'])
parkinson_2['participant_id'] = 'parkinson_2'
parkinson_2['label'] = 'old_parkinson'
parkinson_2['group']=np.divmod(np.arange(len(parkinson_2)),timewindow)[0]+1
parkinson_2.to_csv('dataset_parkinson_2.csv')

parkinson_3 = pd.DataFrame(np.loadtxt('pd3-si.txt'), columns=['time','gait'])
parkinson_3['participant_id'] = 'parkinson_3'
parkinson_3['label'] = 'old_parkinson'
parkinson_3['group']=np.divmod(np.arange(len(parkinson_3)),timewindow)[0]+1
parkinson_3.to_csv('dataset_parkinson_3.csv')

parkinson_4 = pd.DataFrame(np.loadtxt('pd4-si.txt'), columns=['time','gait'])
parkinson_4['participant_id'] = 'parkinson_4'
parkinson_4['label'] = 'old_parkinson'
parkinson_4['group']=np.divmod(np.arange(len(parkinson_4)),timewindow)[0]+1
parkinson_4.to_csv('dataset_parkinson_4.csv')

parkinson_5 = pd.DataFrame(np.loadtxt('pd5-si.txt'), columns=['time','gait'])
parkinson_5['participant_id'] = 'parkinson_5'
parkinson_5['label'] = 'old_parkinson'
parkinson_5['group']=np.divmod(np.arange(len(parkinson_5)),timewindow)[0]+1
parkinson_5.to_csv('dataset_parkinson_5.csv')

In [5]:
gait_dataset = pd.concat([old_1, old_2, old_3, old_4, old_5, young_1, young_2, young_3, young_4, young_5, parkinson_1,parkinson_2,parkinson_3, parkinson_4, parkinson_5])
gait_dataset.to_csv('dataset_gait_timewindow_20.csv')

In [6]:
gait_dataset

         time    gait participant_id          label  group
0     30.7970  1.0230          old_1    old_general      1
1     31.8200  1.0300          old_1    old_general      1
2     32.8500  1.0170          old_1    old_general      1
3     33.8670  1.0270          old_1    old_general      1
4     34.8930  1.0430          old_1    old_general      1
..        ...     ...            ...            ...    ...
240  294.0400  1.1500    parkinson_5  old_parkinson     13
241  295.1767  1.1367    parkinson_5  old_parkinson     13
242  296.2567  1.0800    parkinson_5  old_parkinson     13
243  297.3667  1.1100    parkinson_5  old_parkinson     13
244  298.5000  1.1333    parkinson_5  old_parkinson     13

[9144 rows x 5 columns]