In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
result_baseline = pd.read_csv('evaluation_baseline_SVM.csv', usecols=['recall_bs_tr','recall_bs_ts','F1_bs_tr','F1_bs_ts'])
result_entropy = pd.read_csv('evaluation_entropy_SVM.csv', usecols=['recall_bs_tr','recall_bs_ts','F1_bs_tr','F1_bs_ts'])

In [3]:
result_baseline_f1_tr = pd.DataFrame(result_baseline['F1_bs_tr'])
result_baseline_f1_tr.columns = ['value']
result_baseline_f1_tr['group'] = 'F1_tr'

result_baseline_f1_ts = pd.DataFrame(result_baseline['F1_bs_ts'])
result_baseline_f1_ts.columns = ['value']
result_baseline_f1_ts['group'] = 'F1_ts'

result_baseline_recall_tr = pd.DataFrame(result_baseline['recall_bs_tr'])
result_baseline_recall_tr.columns = ['value']
result_baseline_recall_tr['group'] = 'recall_tr'

result_baseline_recall_ts = pd.DataFrame(result_baseline['recall_bs_ts'])
result_baseline_recall_ts.columns = ['value']
result_baseline_recall_ts['group'] = 'recall_ts'

result_baseline_n = pd.concat([result_baseline_f1_tr, result_baseline_f1_ts])
result_baseline_n = pd.concat([result_baseline_n, result_baseline_recall_tr])
result_baseline_n = pd.concat([result_baseline_n, result_baseline_recall_ts]).reset_index(drop=True)
result_baseline_n['Features'] = 'baseline'
result_baseline_n

        value      group  Features
0    0.638554      F1_tr  baseline
1    0.493506      F1_tr  baseline
2    0.634921      F1_tr  baseline
3    0.603015      F1_tr  baseline
4    0.652850      F1_tr  baseline
..        ...        ...       ...
115  0.534884  recall_ts  baseline
116  0.500000  recall_ts  baseline
117  0.647059  recall_ts  baseline
118  0.634146  recall_ts  baseline
119  0.636364  recall_ts  baseline

[120 rows x 3 columns]

In [4]:
result_entropy_f1_tr = pd.DataFrame(result_entropy['F1_bs_tr'])
result_entropy_f1_tr.columns = ['value']
result_entropy_f1_tr['group'] = 'F1_tr'

result_entropy_f1_ts = pd.DataFrame(result_entropy['F1_bs_ts'])
result_entropy_f1_ts.columns = ['value']
result_entropy_f1_ts['group'] = 'F1_ts'

result_baseline_entropy_tr = pd.DataFrame(result_entropy['recall_bs_tr'])
result_baseline_entropy_tr.columns = ['value']
result_baseline_entropy_tr['group'] = 'recall_tr'

result_baseline_entropy_ts = pd.DataFrame(result_entropy['recall_bs_ts'])
result_baseline_entropy_ts.columns = ['value']
result_baseline_entropy_ts['group'] = 'recall_ts'

result_entropy_n = pd.concat([result_entropy_f1_tr, result_entropy_f1_ts])
result_entropy_n = pd.concat([result_entropy_n, result_baseline_entropy_tr])
result_entropy_n = pd.concat([result_entropy_n, result_baseline_entropy_ts]).reset_index(drop=True)
result_entropy_n['Features'] = 'entropy'
result_entropy_n

        value      group Features
0    0.698925      F1_tr  entropy
1    0.654762      F1_tr  entropy
2    0.623529      F1_tr  entropy
3    0.662921      F1_tr  entropy
4    0.705882      F1_tr  entropy
..        ...        ...      ...
115  0.625000  recall_ts  entropy
116  0.702703  recall_ts  entropy
117  0.565217  recall_ts  entropy
118  0.608696  recall_ts  entropy
119  0.687500  recall_ts  entropy

[120 rows x 3 columns]

In [5]:
result_all = pd.concat([result_baseline_n, result_entropy_n], axis=0)
# result_all.drop(['group_2'],axis=1, inpl÷ce=True)
result_all

        value      group  Features
0    0.638554      F1_tr  baseline
1    0.493506      F1_tr  baseline
2    0.634921      F1_tr  baseline
3    0.603015      F1_tr  baseline
4    0.652850      F1_tr  baseline
..        ...        ...       ...
115  0.625000  recall_ts   entropy
116  0.702703  recall_ts   entropy
117  0.565217  recall_ts   entropy
118  0.608696  recall_ts   entropy
119  0.687500  recall_ts   entropy

[240 rows x 3 columns]

In [ ]:
ax = sns.boxplot(x="group", y="value", hue="Features",data=result_all, palette="Set3")
# plt.ylim(0,1)
plt.savefig('plot_result_MLP.png', dpi=100)